### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by jxnblk** [styled-system/styled-system#475]
This is a WIP issue to track potential changes for the next major version.

- [x] Remove `propTypes` from core 
- [x] Add optional package for React `propTypes`
- [x] Remove conversion of unitless numbers into pixels (most CSS-in-JS libraries support this by default now)
- [x] Setup monorepo with Yarn workspaces and Lerna
- [x] Split style functions into separate packages #281
- [x] Create separate `variants` package
- [x] Create separate `propTypes` package
- [x] Create utilities package with `themeGet`, etc
- [x] ~~Remove support for implicit breakpoints~~
- [x] Use `sizes` key per the [Theme Specification](https://system-ui.com/theme/)
- [x] ~~(Under consideration) remove fractional width support – if you make use of this feature, please speak up~~
- [x] Move experimental `css` and/or JSX pragma packages into monorepo
- [x] Move `should-forward-prop` package into monorepo

**Notes**

- For the monorepo setup, and all-in-one package should be created to make migration from v4 to v5 as easy as possible

cc @neoziro

**Comment by pete-redmond-cko** [comment]
@jxnblk what about writing it in TypeScript?

**Comment by johno** [comment]
This all sounds great to me! Totally on board with splitting up different concerns and extra features into separate packages to keep the weight of core down.

> Remove support for implicit breakpoints

Does this mean adding a `0` breakpoint for mobile-first architectures?

> (Under consideration) remove fractional width support – if you make use of this feature, please speak up

I'd be curious why it's under consideration? I'm assuming because it removes some complexity from the codebase? I make heavy use of the feature but am definitely not opposed to removing it. More curious than anything.

**Comment by jxnblk** [comment]
I think @neoziro can elaborate on the breakpoints some more, but I think it means that object values must use defined keys for breakpoints as opposed to using undefined keys for the non-scoped styles. I assume this isn't a change to how array values are parsed

The thinking with `width` is that it's one of the few odd-balls in here. I do like it, but it does behave quite differently from the rest of the props. The other issue is that if `width` supports a `theme.sizes` scale, then `1` would be ambiguous as to whether it references `100%` or `theme.sizes[1]`. I'm still not sure what the best approach here is, so would love to hear more people's thoughts

**Comment by cereallarceny** [comment]
@jxnblk One of my biggest frustrations in styled system currently is the lack of a width key.  It becomes super awkward when having to make something a perfect square (or circle with added border radius).  Perhaps I simply haven't seen how to do this correctly, but I end up having to use something like themeGet to set the width based on my `heights` key in my theme... ugly.

**Is there a better way?**

Likewise, and I should mention this is my own problem, I haven't found a way in my code editor to do fractions without my autocomplete plugin thinking I'm trying to write a self-closing tag.  This can be frustrating when writing JSX where I write a shit-ton of self-closing tags.  Simply writing `1/2` ends up writing `1/>2` every time.  I can't figure out how to turn this off or make the autocomplete plugin more intelligent, so I just deal with it.

While it's definitely not preferable to write absurd decimal places (`0.333333.......`) instead of `1/3`, perhaps there's room to actually turn these units into their own scale.  In my opinion, this would likely have to be a named scale.  Perhaps something like the following:

```js
widths: {
  full: 1,
  half: 0.5,
  third: 0.3333,  // I mean, do I really need another 3 here?
  fourth: 0.25,
  sixth: 0.1666,
  twoThirds: 0.6666,
  threeFourths: 0.75,
  // I rarely use beyond these in a 12-column system anyhow
},
// ... rest of my theme file
```

> The other issue is that if width supports a theme.sizes scale, then 1 would be ambiguous as to whether it references 100% or theme.sizes[1].

Barring my example proposal from above, the easy solution here would be to have styled system's internal parser just look for a standard unit of measurement inside the value.  For instance, if your value ends in `%`, `px`, `em`, or some other obvious measurement, then use it as such... otherwise reference the theme.  I don't think you'd find that many users that would have a use case beyond that.

**Comment by neoziro** [comment]
Actually, with my PR, if you define `widths: [0, 20]` in theme, `width={1}` will be `width: 20px;`. I think it is the expected behaviour. Also using array to describe properties is often not good. So prefer objects and all will be fine!

**Comment by cereallarceny** [comment]
@neoziro I think that's actually the kind of problem @jxnblk was trying to avoid.  Perhaps I misunderstand...

Although I definitely agree that if there's going to be a `widths` key in the theme that it shouldn't be array based.

**Comment by neoziro** [comment]
Yeah I know, but I think they can't be avoided, @jxnblk what do you think?

**Comment by cereallarceny** [comment]
I put out a pseudo-proposal in my previous on how we might avoid this problem.  I'm happy to elaborate on it further if need me (or pick up a PR).  Either way, happy to help in whatever direction styled-system goes in!  😄

**Comment by chasemccoy** [comment]
Just wanted to pop in here and say that me and my team makes major use of fractional widths!

**Comment by neoziro** [comment]
To be clear we are not talking about fractional width. Just about « 1 » that will not be 100% if you provide a key with another thing in theme.widths.

**Comment by johnpolacek** [comment]
I use fractional widths. They are intuitive and expressive. Setting up a width key feels like over-configuration to me. Use whatever widths work for your design, let your build process do the rest.

**Comment by mortnod** [comment]
I support the move to remove fractional widths. While I love its simplicity, it feels inconsistent with how the rest of Styled System works.

More troubling than inconsistency is the fact that it kinda blocks the introduction of a width scale (since `1` can mean `100%` or `size[1]`). Coming from Tachyons, I was very surprised when I discovered this functionality was not built in and ended up having to create my own using the `style` utility.

**Comment by cereallarceny** [comment]
@jxnblk What would you think instead about offering a `width` key on the theme just like `height`, `maxWidth`, `maxHeight`, etc... allowing for people to set their width as a prop just like any other key in their theme.  You could also then have a `fWidth` and/or `fractionWidth` prop that doesn't correspond to any key on the theme, but offers the existing width functionality with fraction support.  While I certainly think fractional widths have their place, particularly when writing a grid system in styled-system, I've found numerous occasions in creating my own UI library that demand some sort of width key theme support.

If you'd like, I would be happy to write a PR on such a spec.

**Comment by jxnblk** [comment]
@cereallarceny I think the plan is to use the `theme.sizes` scale for all dimensions, like outlined in the theme spec. If fractional widths are still supported in the next version, then maybe `0` and `1` would reference e.g. `theme.sizes[1]` and use that value if it exists

**Comment by cereallarceny** [comment]
Perfect!  I hadn't seen the link posted in your first message (I suppose you added it after I first replied to this thread).  I like what you're proposing in there @jxnblk - is there some way to contribute to the v5 rewrite?  I'd love to work on some of the issues you outline above, including converting height, width, and max/min height/width over to a `spaces` key... how could I get started?

**Comment by cereallarceny** [comment]
Either way @jxnblk, I don't think fractional widths have to be lost for good.  We could just add a `fractionalWidth` prop with an `fWidth` alias.  I can't imagine that adding much, if any, reasonable overhead to the library.  It would allow users to support both and would allow existing users who enjoy fractional width an easier path to upgrading.  At least, it would sure lessen the breaking changes involved in upgrading.

**Comment by jxnblk** [comment]
@cereallarceny I'm refactoring the core code base with v5 – should have a PR up before long. As for something like a `fractionWidth` prop, it's an interesting approach, but *would* mean a breaking change for everyone currently using v4 (and potentially a lot of prop name changes), and I'd rather keep the upgrade path as simple as possible

**Comment by cereallarceny** [comment]
Fair, but wouldn't it already be a breaking change if you're dropping
fractional width support on the width prop anyhow?

**Comment by jxnblk** [comment]
Closing this and tracking in #513
